---
title: "Neurobehavioral Scatterplots"
author: "Jasen Zhang"
date: "7/27/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
library(lsmeans)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

# Scatterplots

```{r}
response_vars <- c('iic', 'isc', 'inhibition', 'attention_inhibitory_control')


covariates <- c('age', 'race', 'gender', 'days_after_mdh', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag')

all_3_timepoints <- c(T,T,T,T)






distance_vars <- c('dist_house_plant_log', 'ha_200m_log')

distance_vars_graph <- c('Distance From Home to Nearest Plantation', 'Area of Plantation within 200m')

response_vars_graph <- c('IIC', 'ISC', 'Inhibition Subdomain', 'Attention Inhibitory Control Domain')

graphs <- list()
graph_count <- 1
 
for(k in 1:length(response_vars)){ #1 to 15
  for(l in 1:length(distance_vars)){ # 1 to 5
    if(all_3_timepoints[k]){
      temp_range <- c(1,2,3)
    }
    else{
      temp_range <- c(1,3)
    }
    for(m in temp_range){
      df3_long <- df2_long %>% filter(Index == m)

      i <- response_vars[k]
      j <- distance_vars[l]
      
      graph_y_name <- response_vars_graph[k]
      graph_x_name <- distance_vars_graph[l]
      
      df4_long <- df3_long %>% select('Index', i, j, covariates) %>%
        na.omit() %>%
        filter(!!as.name(j) != 0)
      
      print(nrow(df4_long))
      
      distances <- dplyr::pull(df4_long, j)
      
      num_layers <- floor(length(unique(distances)) * 0.8)
      
      layers <- 1:num_layers/num_layers
      layers <- 0:(num_layers-1)/num_layers
      layers2 <- quantile(distances, layers)
    
      quantile_index <- integer(nrow(df4_long)) + 1
      for(n in layers2){
        gain_one <- as.numeric(distances > n)
        quantile_index <- quantile_index + gain_one
      }
      df4_long$layers <- factor(quantile_index)
    
  
    
      temp <- paste(covariates, collapse = ' + ')                     #eq: y_vars ~ met + covariates
      eq2 <- paste(i, temp, sep = ' ~ ')
  
      eq2 <- paste(eq2, 'layers', sep = ' + ')
      
      model = lm(formula(eq2), data = df4_long)
      model2 <- lsmeans(model, specs = 'layers')
      sum4 <- summary(model2)
      sum5 <- sum4 %>% select('layers', 'lsmean')
      colnames(sum5) <- c('layers', 'lsmean_y')
    
    
      cov_layers <- df4_long$layers
      lsmean_outcome <- c()
      for(n in cov_layers){
        temp <- sum5 %>% filter(layers == n)
        temp2 <- as.numeric(temp[2])                             #extracting the lsmean_y value
        lsmean_outcome <- append(lsmean_outcome, temp2)
      }
      
      df4_long$adjusted_outcome <- lsmean_outcome
      
      loess_eq1 <- paste('adjusted_outcome', j, sep = ' ~ ')
      temp <- predict(loess(formula(loess_eq1), data = df4_long, span = 0.75), se=TRUE)              #get loess the normal way
      df4_long$loess <- temp$fit
      df4_long$lower <- temp$fit - 1.96 * temp$se.fit
      df4_long$upper <- temp$fit + 1.96 * temp$se.fit
      
      if(m == 1){
        df5_1 <- df4_long
      }
      if(m == 2){
        df5_2 <- df4_long
      }
      if(m == 3){
        df5_3 <- df4_long
      }
    }
      
    #get outlier_df
      
  
    
    graph_title <- paste(i, j, sep = ' vs ')

    # y_min <- y_mins[i]
    # y_max <- y_maxes[i]
    # x_min <- x_mins[l]
    # x_max <- x_maxes[l]
    
    x_min <- 1
    x_max <- 2000
    y_min <- 0
    y_max <- 10


    ylab_name <- graph_y_name
    
    xlab_name <- graph_x_name
    
    if(! all_3_timepoints[k]){

      g1  <- ggplot() + 
        geom_point(data = df5_1,         aes(x = exp(!!as.name(j)), y = adjusted_outcome), color = 'red', size = 0.6, alpha = 0.3) + 
        geom_line(data = df5_1,          aes(x = exp(!!as.name(j)), y = loess), color = 'red', size = 0.6) +
        geom_ribbon(data = df5_1,        aes(ymin = lower, ymax = upper, x = exp(!!as.name(j))), fill = 'red', linetype=1, alpha=0.1) +
  
        geom_point(data = df5_3,         aes(x = exp(!!as.name(j)), y = adjusted_outcome), color = 'blue', size = 0.6, alpha = 0.3) + 
        geom_line(data = df5_3,          aes(x = exp(!!as.name(j)), y = loess), color = 'blue', size = 0.6) +
        geom_ribbon(data = df5_3,        aes(ymin = lower, ymax = upper, x = exp(!!as.name(j))), fill = 'blue', linetype=1, alpha=0.1)
    }
    
    else{
      g1 <- ggplot() + 
        geom_point(data = df5_1,         aes(x = exp(!!as.name(j)), y = adjusted_outcome, color = 'summer 2008'), size = 0.6, alpha = 0.3) + 
        geom_line(data = df5_1,          aes(x = exp(!!as.name(j)), y = loess, color = 'summer 2008'),  size = 0.6) +
        geom_ribbon(data = df5_1,        aes(ymin = lower, ymax = upper, x = exp(!!as.name(j)), fill = 'summer 2008'), linetype=1, alpha=0.1) +
  
        geom_point(data = df5_3,         aes(x = exp(!!as.name(j)), y = adjusted_outcome, color = 'summer 2016'), size = 0.6, alpha = 0.3) + 
        geom_line(data = df5_3,          aes(x = exp(!!as.name(j)), y = loess, color = 'summer 2016'),  size = 0.6) +
        geom_ribbon(data = df5_3,        aes(ymin = lower, ymax = upper, x = exp(!!as.name(j)), fill = 'summer 2016'), linetype=1, alpha=0.1) + 
        
        geom_point(data = df5_2,         aes(x = exp(!!as.name(j)), y = adjusted_outcome, color = 'spring 2016'),  size = 0.6, alpha = 0.3) + 
        geom_line(data = df5_2,          aes(x = exp(!!as.name(j)), y = loess, color = 'spring 2016'), size = 0.6) +
        geom_ribbon(data = df5_2,        aes(ymin = lower, ymax = upper, x = exp(!!as.name(j)), fill = 'spring 2016'), linetype=1, alpha=0.1)      
    }
    g1 <- g1 + 
      # ylim(y_min, y_max) +
      # scale_x_continuous(trans='log10', limits = c(x_min, x_max)) +   
      scale_x_continuous(trans='log10') +
      xlab(xlab_name) + 
      ylab(ylab_name) + 
      ylim(-1, 15) + 
      scale_color_manual(values=c('red', 'green', 'blue'), 
                     name="Legend",
                     breaks=c("summer 2008","spring 2016", "summer 2016")) + 
      scale_fill_manual(values=c('red', 'green', 'blue'), 
               name="Legend",
               breaks=c("summer 2008","spring 2016", "summer 2016")) + 
      theme(plot.title = element_text(size = 6),
            axis.text=element_text(size=8),
            axis.title=element_text(size=8),
            legend.position = c(0.15, 0.9),
            legend.background = element_rect(fill = 'transparent'),
            legend.text = element_text(size = 5),
            legend.title = element_blank(),
            legend.key.size = unit(0.5, 'cm'))

    
    graphs[[graph_count]] <- g1
    graph_count <- graph_count + 1      
    

  }
}

lay2 <- rbind(c(1,2),
              c(3,4))

plot_dir <- paste(substr(dir,1, nchar(dir)-4), "Figures/Final/5_Neurobehavioral_LSMeans_Loess_Curves_PAPER.pdf", sep = '')
pdf(plot_dir) 


grid.arrange(graphs[[1]],
             graphs[[2]],
             graphs[[3]],
             graphs[[4]], layout_matrix = lay2)

grid.arrange(graphs[[5]],
             graphs[[6]],
             graphs[[7]],
             graphs[[8]], layout_matrix = lay2)


dev.off()
```
