---
title: "summer"
author: "Jasen"
date: "7/7/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}
response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                   'auditory_attention_response_set', 'inhibition',
                   'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')

temp_factor <- df2_long$dist_house_plant >= 150
temp_factor[temp_factor == T] <- 'above_150'
temp_factor[temp_factor == F] <- 'below_150'

temp_factor <- as.factor(temp_factor)

df3_long <- df2_long %>% mutate(dist_house_plant_factor = temp_factor)




distance_vars <- c('dist_house_plant_factor')

pvalues <- data.frame()

output_dir <- paste(substr(dir,1, nchar(dir)-4), "Figures/Neurobehavioral/5b_Neurobehavioral_Temporal_Models.txt", sep = '')
sink(output_dir)
for(k in 1:length(response_vars)){
  pval_array <- c()
  for(j in distance_vars){
    covariates <- c('age', 'race', 'gender', 'Index', 'days_after_mdh', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag')
    
    i <- response_vars[k]
    
    important_vars <- c('nid', covariates, i, j)
    
    if(i == 'iic' | i == 'isc'){
      important_vars <- append(important_vars, 'inc')
      covariates <- append(covariates, 'inc')
    }
    if(i == 'mffdts'){
      important_vars <- append(important_vars, 'mffts')
      covariates <- append(covariates, 'mffts')
    }
    
    
    
    df4_long <- df3_long %>% select(important_vars) %>% na.omit()
    
    if(0 %in% table(df4_long$Index)){
      df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
    }
    
    eq <- paste(i, j, sep = ' ~ ')
    temp <- paste(covariates, collapse = ' + ')
    eq <- paste(eq, temp, sep = ' + ')
    
    m <- geeglm(formula = formula(eq), id = nid, data=df4_long,
                family='gaussian', corstr="exchangeable")
    s <- summary(m)
    
    
    
    s_coeffs <- s$coefficients
    pvalue <- s_coeffs[2,4]
    
    beta_sign_positive <- (s_coeffs[2,1] > 0)
    if(beta_sign_positive){
      the_sign <- 1
    } else{
      the_sign <- -1
    }
    
    pval_array <- append(pval_array, pvalue * the_sign)
    
    print(eq)
    print(table(df4_long$Index))
    print(s)
    print('-------------------------------')
  }
  pvalues <- rbind(pvalues, pval_array)
}
sink()

```

#create pvalue matrix

```{r}
pvalues2 <- t(pvalues)
rownames(pvalues2) <- distance_vars
colnames(pvalues2) <- response_vars

name <- c('Figures/Neurobehavioral/5b_NEPSY_Pvalues.csv')
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(pvalues2, file = data_dir)

pvalues3 <- pvalues2
pvalues3[abs(pvalues3) > 0.05] <- NA

name <- c('Figures/Neurobehavioral/5b_NEPSY_Pvalues_significant.csv')
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(pvalues3, file = data_dir)
```