---
title: "Models"
author: "Jasen Zhang"
date: "8/21/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
library(lsmeans)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}
response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                   'auditory_attention_response_set', 'inhibition',
                   'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')

#restricting to a and c timepoints

df3_long <- df2_long 
df3_long$Index <- factor(df3_long$Index, levels = c(1,2,3))

# two_levels <- c(F,F,F,F,F,T,T,T,T,T,T,
#                 F,T,T,T)

area_var <- c('50','100','150','200','300','500','1000')
area_var <- paste('ha_', area_var, sep = '')
area_var <- paste(area_var, 'm', sep = '')
area_var_log <- paste(area_var, '_log', sep = '')

distance_vars <- c('dist_house_plant_log', area_var_log)

pvalues <- data.frame()
ests <- data.frame()
contrasts <- data.frame()
CIs <- data.frame()

output_dir <- paste(substr(dir,1, nchar(dir)-4), "Figures/Neurobehavioral/5d3_Neurobehavioral_LSmeans_20_80.txt", sep = '')
sink(output_dir)
for(k in 1:length(response_vars)){
  est_array <- c()
  pval_array <- c()
  contrast_array <- c()    
  for(j in distance_vars){
    two_levels <- F
    covariates <- c('age', 'Index', 'octoberness', 'race', 'gender', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag')
    
    i <- response_vars[k]
    
    important_vars <- c('nid', covariates, i, j)
    
    if(i == 'iic' | i == 'isc' | i == 'inhibition'){
      important_vars <- append(important_vars, 'inc')
      covariates <- append(covariates, 'inc')
    }
    if(i == 'mffdts' | i == 'memory_and_learning'){
      important_vars <- append(important_vars, 'mffts')
      covariates <- append(covariates, 'mffts')
    }
    
    temp_output_name <- paste(j, 'binary', sep = '_')
    

    

    
    df4_long <- df3_long %>% select(important_vars) %>% na.omit()
    
    temp_vec <- dplyr::pull(df4_long, j)
    
    temp_vec2 <- rep(0, length(temp_vec))
    
    temp_vec2[temp_vec > quantile(temp_vec, 0.80)] <- 'above 80%'
    temp_vec2[temp_vec <= quantile(temp_vec, 0.20)] <- 'below 20%'
    
    df4_long <- df4_long %>% mutate(!!as.name(temp_output_name) := temp_vec2)
    df4_long <- df4_long %>% filter(!!as.name(temp_output_name) != 0)
    df4_long <- df4_long %>% mutate(!!as.name(temp_output_name) := as.factor(!!as.name(temp_output_name)))
        
    if(0 %in% table(df4_long$Index)){
      df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
      two_levels <- T
    }
    
  
    temp <- paste(covariates, collapse = ' + ')
    eq <- paste(i, temp, sep = ' ~ ')
    eq <- paste(eq, temp_output_name, sep = ' + ')
    
    m <- geeglm(formula = formula(eq), id = nid, data=df4_long,
                family=gaussian, corstr="exchangeable")

    cat('equation: ', eq, '\n')
    cat('20 percentile:', exp(quantile(temp_vec, 0.20)), '\n')
    cat('80 percentile:', exp(quantile(temp_vec, 0.80)), '\n')
    cat('lsmeans results: \n')
    
    temp_formula <- paste('pairwise', temp_output_name, sep = ' ~ ')
    
    print(lsmeans(m, formula(temp_formula)))
    
    #extract the p-value
    
    wow <- lsmeans(m, formula(temp_formula))
    wow2 <- unname(summary(wow$contrasts)[6])
    contrast_array <- append(contrast_array, wow2)      
    
    CI_array <- unname(summary(wow$lsmeans)[c(2,5,6)])
    CI_array <- cbind(CI_array, c('above 80%', 'below 20%'))
    CI_array <- cbind(CI_array, rep(i,2))
    CI_array <- cbind(CI_array, rep(j,2))
    CIs <- rbind(CIs, CI_array)
    
    cat('------------------------------------------------------------------------------\n')
    
  }
  contrasts <- rbind(contrasts, contrast_array)  

}

colnames(contrasts) <- distance_vars
rownames(contrasts) <- response_vars

name <- c('Figures/Neurobehavioral/5d3_Neurobehavioral_LSmeans_20_80_percentiles_Pvalues.csv')
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(contrasts, file = data_dir)

contrasts_sig <- contrasts
contrasts_sig[abs(contrasts_sig) > 0.05] <- NA

name <- c('Figures/Neurobehavioral/5d3_Neurobehavioral_LSmeans_20_80_percentiles_Pvalues_Sig.csv')
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(contrasts_sig, file = data_dir)


```