---
title: "Models"
author: "Jasen Zhang"
date: "8/21/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
library(lsmeans)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}

nepsy_thresh <- c(10,15,20,25,30,35,40,45)
nepsy_thresh <- c(10, 20,30,40,50,60,70)
for(thresh in nepsy_thresh){
  print(thresh)

  response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                     'auditory_attention_response_set', 'inhibition',
                     'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')
  
  #restricting to a and c timepoints
  
  df3_long <- df2_long 
  df3_long$Index <- factor(df3_long$Index, levels = c(1,2,3))
  
  # two_levels <- c(F,F,F,F,F,T,T,T,T,T,T,
  #                 F,T,T,T)
  
  area_var <- c('50','100','150','200','300','500','1000')
  area_var <- paste('ha_', area_var, sep = '')
  area_var <- paste(area_var, 'm', sep = '')
  area_var_log <- paste(area_var, '_log', sep = '')
  
  distance_vars <- c('dist_house_plant_log', area_var_log)
  
  estimates <- data.frame()
  lows <- data.frame()
  highs <- data.frame()
  contrasts <- data.frame()
  
  temp_name <- paste('Figures/Neurobehavioral/5d4_Neurobehavioral_LSmeans', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.txt', sep = '')
  
  output_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
  sink(output_dir)
  for(k in 1:length(response_vars)){
    est_array <- c()
    low_array <- c()
    high_array <- c()
    pval_array <- c()
    contrast_array <- c()    
    for(j in distance_vars){
      two_levels <- F
      covariates <- c('age', 'Index', 'days_after_mdh', 'race', 'gender', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag')
      
      i <- response_vars[k]
      
      if(j == 'dist_house_plant_log'){
        thresh2 <- thresh
      } else{
        thresh2 <- 100 - thresh
      }
      
      important_vars <- c('nid', covariates, i, j)
      
      if(i == 'iic' | i == 'isc' | i == 'inhibition'){
        important_vars <- append(important_vars, 'inc')
        covariates <- append(covariates, 'inc')
      }
      if(i == 'mffdts' | i == 'memory_and_learning'){
        important_vars <- append(important_vars, 'mffts')
        covariates <- append(covariates, 'mffts')
      }
      
      temp_output_name <- paste(j, 'binary', sep = '_')
      
  
      
  
      
      df4_long <- df3_long %>% select(important_vars) %>% na.omit()
      
      temp_vec <- dplyr::pull(df4_long, j)
      
      temp_vec2 <- rep(0, length(temp_vec))
      
      temp_name_1 <- paste('above', as.character(thresh2), sep = ' ')
      temp_name_1 <- paste(temp_name_1, '%', sep = ' ')
  
      temp_name_2 <- paste('below', as.character(thresh2), sep = ' ')
      temp_name_2 <- paste(temp_name_2, '%', sep = ' ')    
          
      temp_vec2[temp_vec > quantile(temp_vec, 0.01* thresh2)] <- temp_name_1
      temp_vec2[temp_vec <= quantile(temp_vec, 0.01 * thresh2)] <- temp_name_2
      
      df4_long <- df4_long %>% mutate(!!as.name(temp_output_name) := temp_vec2)
      df4_long <- df4_long %>% filter(!!as.name(temp_output_name) != 0)
      df4_long <- df4_long %>% mutate(!!as.name(temp_output_name) := as.factor(!!as.name(temp_output_name)))
          
      if(0 %in% table(df4_long$Index)){
        df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
        two_levels <- T
      }
      
    
      temp <- paste(covariates, collapse = ' + ')
      eq <- paste(i, temp, sep = ' ~ ')
      eq <- paste(eq, temp_output_name, sep = ' + ')
      
      m <- geeglm(formula = formula(eq), id = nid, data=df4_long,
                  family=gaussian, corstr="exchangeable")
  
      cat('equation: ', eq, '\n')
      
      temp_name_1 <- paste(as.character(thresh2), 'percentile:', sep = ' ')
      
      cat(temp_name_1, exp(quantile(temp_vec, 0.01 * thresh2)), '\n')
      cat('lsmeans results: \n')
      
      temp_formula <- paste('pairwise', temp_output_name, sep = ' ~ ')
      
      print(confint(lsmeans(m, formula(temp_formula))))
      
      #extract the p-value
      
      wow <- lsmeans(m, formula(temp_formula))
      wow2 <- unname(summary(wow$contrasts)[6])
      contrast_array <- append(contrast_array, wow2)      
      
      #extract the est, lower, and upper
      
      wow3 <- confint(wow)
      est <- unname(wow3$contrasts)[2]
      lower <- unname(wow3$contrasts)[5]
      upper <- unname(wow3$contrasts)[6]
      
      est_array <- append(est_array, est)
      low_array <- append(low_array, lower)
      high_array <- append(high_array, upper)      
      
      cat('------------------------------------------------------------------------------\n')
      
    }
    contrasts <- rbind(contrasts, contrast_array)   
    estimates <- rbind(estimates, est_array)
    lows <- rbind(lows, low_array)
    highs <- rbind(highs, high_array)    
  }
  
  colnames(contrasts) <- distance_vars
  rownames(contrasts) <- response_vars
  
  temp_name <- paste('Figures/Neurobehavioral/5d4_Neurobehavioral_LSmeans', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, 'percentiles_Pvalues.csv', sep = '_')
  
  name <- c(temp_name)
  data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
  write.csv(contrasts, file = data_dir)
  
  contrasts_sig <- contrasts
  contrasts_sig[abs(contrasts_sig) > 0.05] <- NA
  
  temp_name <- paste('Figures/Neurobehavioral/5d4_Neurobehavioral_LSmeans', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, 'percentiles_Pvalues_Sig.csv', sep = '_')
  
  name <- c(temp_name)
  data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
  write.csv(contrasts_sig, file = data_dir)
  
  #graphs
  
  highs2 <- t(highs)
  rownames(highs2) <- distance_vars
  colnames(highs2) <- paste(response_vars, 'high', sep = '_')
  
  lows2 <- t(lows)
  rownames(lows2) <- distance_vars
  colnames(lows2) <- paste(response_vars, 'low', sep = '_')
  
  estimates2 <- t(estimates)
  rownames(estimates2) <- distance_vars
  colnames(estimates2) <- response_vars
  
  estimates3 <- as.data.frame(estimates2)
  lows3 <- as.data.frame(lows2)
  highs3 <- as.data.frame(highs2)
   
  
  temp_name <- factor(rownames(estimates3), levels = c('dist_house_plant_log', 'ha_50m_log', 'ha_100m_log', 'ha_150m_log', 'ha_200m_log', 'ha_300m_log', 'ha_500m_log', 'ha_1000m_log'))
  
  all_results <- cbind(estimates3, lows3, highs3)
  all_results <- all_results %>% mutate(var_name = temp_name) %>%
    mutate(sig_line = rep(0,nrow(all_results)))
  
  
  
  
  nepsy_names <- response_vars
  
  graphs <- list()
  graph_index <- 1
  
  for(i in nepsy_names){
    est_name <- i
    low_name <- paste(i, 'low', sep = '_')
    high_name <- paste(i, 'high', sep = '_')
    temp_title <- paste(i, 'NEPSY Score', sep = ' ')
    
    g1 <- ggplot(data = all_results) +
      geom_errorbar(aes(x = var_name, y = !!as.name(i), ymin = !!as.name(low_name), ymax = !!as.name(high_name)), width = 0.5) + 
      geom_point(aes(x = var_name, y = !!as.name(i))) + 
      geom_line(aes(x = var_name, y = sig_line, group = 1), color = 'red') + 
      theme(axis.text.x = element_text(angle = 30, hjust = 1, size = 7)) + 
      ylab('Estimate') + 
      xlab('Variable') + 
      ggtitle(temp_title)
    graphs[[graph_index]] <- g1
    graph_index <- graph_index + 1
  }
  
  
  
  
    
  lay2 <- rbind(c(1,2),
                c(3,4))
  
  temp_title <- paste('Figures/Neurobehavioral/5d4_LSMeans_Estimate_Graphs', as.character(thresh), sep = '_')
  temp_title <- paste(temp_title, '.pdf', sep = '')
  
  plot_dir <- paste(substr(dir,1, nchar(dir)-4), temp_title, sep = '')
  pdf(plot_dir) 
  
  i <- 0 
  wow <- graph_index - 1
  while(i < wow){
    if(wow - i == 1){
      grid.arrange(graphs[[i+1]], layout_matrix = lay2)    
    }
    if(wow - i == 2){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], layout_matrix = lay2)    
    }  
    if(wow - i == 3){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], 
                   graphs[[i+3]], layout_matrix = lay2)    
    }  
    if(wow - i >= 4){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], 
                   graphs[[i+3]], 
                   graphs[[i+4]], layout_matrix = lay2)    
    }    
  
    i <- i + 4
  }
  
  dev.off()  
  
}

```

```{r}

  
```
