---
title: "summer"
author: "Jasen"
date: "7/7/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}

get_distribution <- function(vec, values){
  results <- c()
  for(i in values){
    result <- mean(vec <= i & vec > (i-1))
    results <- append(results, result)
  }
  results
}


graphs <- list()
graph_index <- 1
  

  
  
response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                   'auditory_attention_response_set', 'inhibition',
                   'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')

#restricting to a and c timepoints

df3_long <- df2_long 
df3_long$Index <- factor(df3_long$Index, levels = c(1,2,3))

# two_levels <- c(F,F,F,F,F,T,T,T,T,T,T,
#                 F,T,T,T)

area_var <- c('50','100','150','200','300','500','1000')
area_var <- paste('ha_', area_var, sep = '')
area_var <- paste(area_var, 'm', sep = '')
area_var_log <- paste(area_var, '_log', sep = '')
area_var_scaled <- paste(area_var, '_scaled', sep = '')
area_var_scaled_log <- paste(area_var, '_scaled_log', sep = '')

distance_vars <- c('dist_house_plant', 'dist_house_plant_log', area_var, area_var_log, area_var_scaled, area_var_scaled_log)
distance_vars <- c('dist_house_plant_log', area_var_log)

percentile_array <- c()
cum_percentile_array <- c()
  

for(k in 1:length(response_vars)){

  

  covariates <- c('age', 'race', 'gender', 'Index', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag', 'days_after_mdh')
    
  i <- response_vars[k]
  
  important_vars <- c('nid', covariates, i)
    
  if(i == 'iic' | i == 'isc' | i == 'inhibition'){
    important_vars <- append(important_vars, 'inc')
    covariates <- append(covariates, 'inc')
  }
  if(i == 'mffdts' | i == 'memory_and_learning'){
    important_vars <- append(important_vars, 'mffts')
    covariates <- append(covariates, 'mffts')
  }
    
    
    
  df4_long <- df3_long %>% select(important_vars) %>% na.omit()
  
  if(0 %in% table(df4_long$Index)){
    df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
  }
  
  binary_outcome <- paste(i, 'binary', sep = '_')
  
  df4_long <- df4_long %>% mutate(!!as.name(binary_outcome) := (!!as.name(i) >= thresh))
  
  #percentiles
  
  percentile_tables <- get_distribution(dplyr::pull(df4_long, i), 1:20)
  cum_percentile_tables <- cumsum(percentile_tables)
  
  
  percentile_array <- rbind(percentile_array, percentile_tables)
  cum_percentile_array <- rbind(cum_percentile_array, cum_percentile_tables)
    
  #figure
  
  est_name <- i
  temp_title <- i
  
  g1 <- ggplot(data = df4_long) +
    geom_histogram(aes(x = !!as.name(i))) + 
    ylab('Frequency') + 
    xlab('Nepsy Score') + 
    ggtitle(temp_title)
  graphs[[graph_index]] <- g1
  graph_index <- graph_index + 1      
}

  
# publish pdf and cdf tables

rownames(percentile_array) <- response_vars
colnames(percentile_array) <- 1:20
rownames(cum_percentile_array) <- response_vars
colnames(cum_percentile_array) <- 1:20

temp_name <- c('Figures/Neurobehavioral/5e3_NEPSY_pdfs.csv')

name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(percentile_array, file = data_dir)
  
temp_name <- c('Figures/Neurobehavioral/5e3_NEPSY_cdfs.csv')

name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(cum_percentile_array, file = data_dir)  
    
lay2 <- rbind(c(1,2),
              c(3,4))

temp_name <- paste('Figures/Neurobehavioral/5e3_Histograms', as.character(thresh), sep = '_')
temp_name <- paste(temp_name, '.pdf', sep = '')

plot_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
pdf(plot_dir) 

i <- 0 
wow <- graph_index - 1
while(i < wow){
  if(wow - i == 1){
    grid.arrange(graphs[[i+1]], layout_matrix = lay2)    
  }
  if(wow - i == 2){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], layout_matrix = lay2)    
  }  
  if(wow - i == 3){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], 
                 graphs[[i+3]], layout_matrix = lay2)    
  }  
  if(wow - i >= 4){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], 
                 graphs[[i+3]], 
                 graphs[[i+4]], layout_matrix = lay2)    
  }    

  i <- i + 4
}

dev.off()

```