---
title: "summer"
author: "Jasen"
date: "7/7/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}
nepsy_thresh <- c(2,3,4,5,6,7,8)

for(thresh in nepsy_thresh){
  
  
  response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                     'auditory_attention_response_set', 'inhibition',
                     'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')
  
  #restricting to a and c timepoints
  
  df3_long <- df2_long 
  df3_long$Index <- factor(df3_long$Index, levels = c(1,2,3))
  
  # two_levels <- c(F,F,F,F,F,T,T,T,T,T,T,
  #                 F,T,T,T)
  
  area_var <- c('50','100','150','200','300','500','1000')
  area_var <- paste('ha_', area_var, sep = '')
  area_var <- paste(area_var, 'm', sep = '')
  area_var_log <- paste(area_var, '_log', sep = '')
  area_var_scaled <- paste(area_var, '_scaled', sep = '')
  area_var_scaled_log <- paste(area_var, '_scaled_log', sep = '')
  
  distance_vars <- c('dist_house_plant', 'dist_house_plant_log', area_var, area_var_log, area_var_scaled, area_var_scaled_log)
  distance_vars <- c('dist_house_plant_log', area_var_log)
  
  pvalues <- data.frame()
  estimates <- data.frame()
  lows <- data.frame()
  highs <- data.frame()
  
  temp_name <- paste('Figures/Neurobehavioral/5e_Neurobehavioral_Temporal_Models', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.txt', sep = '')
  
  output_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
  sink(output_dir)
  for(k in 1:length(response_vars)){
    pval_array <- c()
    est_array <- c()
    low_array <- c()
    high_array <- c()
    for(j in distance_vars){
      covariates <- c('age', 'race', 'gender', 'Index', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag', 'days_after_mdh')
      
      i <- response_vars[k]
      
      important_vars <- c('nid', covariates, i, j)
      
      if(i == 'iic' | i == 'isc' | i == 'inhibition'){
        important_vars <- append(important_vars, 'inc')
        covariates <- append(covariates, 'inc')
      }
      if(i == 'mffdts' | i == 'memory_and_learning'){
        important_vars <- append(important_vars, 'mffts')
        covariates <- append(covariates, 'mffts')
      }
      
      
      
      df4_long <- df3_long %>% select(important_vars) %>% na.omit()
      
      if(0 %in% table(df4_long$Index)){
        df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
      }
      
      binary_outcome <- paste(i, 'binary', sep = '_')
      
      df4_long <- df4_long %>% mutate(!!as.name(binary_outcome) := (!!as.name(i) > thresh))
      
      eq <- paste(binary_outcome, j, sep = ' ~ ')
      temp <- paste(covariates, collapse = ' + ')
      eq <- paste(eq, temp, sep = ' + ')
      
      m <- geeglm(formula = formula(eq), id = nid, data=df4_long,
                  family=binomial(link = 'logit'), corstr="exchangeable")
      s <- summary(m)
      
      
      
      s_coeffs <- s$coefficients
      s_confint <- broom::tidy(m, conf.int = T)
      
      temp_est <- as.numeric(s_confint[2,2])
      temp_lower <- as.numeric(s_confint[2,6])
      temp_upper <- as.numeric(s_confint[2,7])
      pvalue <- s_coeffs[2,4]
      
      beta_sign_positive <- (s_coeffs[2,1] > 0)
      if(beta_sign_positive){
        the_sign <- 1
      } else{
        the_sign <- -1
      }
      
      pval_array <- append(pval_array, pvalue * the_sign)
      est_array <- append(est_array, exp(temp_est))
      low_array <- append(low_array, exp(temp_lower))
      high_array <- append(high_array, exp(temp_upper))
      
      print(eq)
      print(table(df4_long$Index))
      print(s)
      print('-------------------------------')
    }
    pvalues <- rbind(pvalues, pval_array)
    estimates <- rbind(estimates, est_array)
    lows <- rbind(lows, low_array)
    highs <- rbind(highs, high_array)
  }
  sink()
  
  #create pvalue matrix
  
  
  estimates2 <- t(estimates)
  rownames(estimates2) <- distance_vars
  colnames(estimates2) <- response_vars
  
  temp_name <- paste('Figures/Neurobehavioral/5e_NEPSY_OR_Estimates', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.csv', sep = '')
  
  name <- c(temp_name)
  data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
  write.csv(estimates2, file = data_dir)
  
  pvalues2 <- t(pvalues)
  rownames(pvalues2) <- distance_vars
  colnames(pvalues2) <- response_vars
  
  temp_name <- paste('Figures/Neurobehavioral/5e_NEPSY_Pvalues', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.csv', sep = '')
  
  name <- c(temp_name)
  data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
  write.csv(pvalues2, file = data_dir)
  
  pvalues3 <- pvalues2
  pvalues3[abs(pvalues3) > 0.05] <- NA
  
  temp_name <- paste('Figures/Neurobehavioral/5e_NEPSY_Pvalues_significant', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.csv', sep = '')
  
  name <- c(temp_name)
  data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
  write.csv(pvalues3, file = data_dir)
  
  
  # create figures
  
  
  highs2 <- t(highs)
  rownames(highs2) <- distance_vars
  colnames(highs2) <- paste(response_vars, 'high', sep = '_')
  
  lows2 <- t(lows)
  rownames(lows2) <- distance_vars
  colnames(lows2) <- paste(response_vars, 'low', sep = '_')
  
  estimates3 <- as.data.frame(estimates2)
  lows3 <- as.data.frame(lows2)
  highs3 <- as.data.frame(highs2)
   
  
  temp_name <- factor(rownames(estimates3), levels = c('dist_house_plant_log', 'ha_50m_log', 'ha_100m_log', 'ha_150m_log', 'ha_200m_log', 'ha_300m_log', 'ha_500m_log', 'ha_1000m_log'))
  
  all_results <- cbind(estimates3, lows3, highs3)
  all_results <- all_results %>% mutate(var_name = temp_name) %>%
    mutate(sig_line = rep(1,nrow(all_results)))
  
  nepsy_names <- response_vars
  
  graphs <- list()
  graph_index <- 1
  
  for(i in nepsy_names){
    est_name <- i
    low_name <- paste(i, 'low', sep = '_')
    high_name <- paste(i, 'high', sep = '_')
    temp_title <- paste(toupper(i), 'NEPSY Score', sep = ' ')
    temp_title <- paste(temp_title, as.character(thresh), sep = ' (')
    temp_title <- paste(temp_title, ')', sep = '')
    
    g1 <- ggplot(data = all_results) +
      geom_errorbar(aes(x = var_name, y = !!as.name(i), ymin = !!as.name(low_name), ymax = !!as.name(high_name)), width = 0.5) + 
      geom_point(aes(x = var_name, y = !!as.name(i))) + 
      geom_line(aes(x = var_name, y = sig_line, group = 1), color = 'red') + 
      theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
      ylab('Estimate') + 
      xlab('Variable') + 
      ggtitle(temp_title)
    graphs[[graph_index]] <- g1
    graph_index <- graph_index + 1
  }
  
  
  
  
    
  lay2 <- rbind(c(1,2),
                c(3,4))
  
  temp_name <- paste('Figures/Neurobehavioral/5e_NEPSY_Model_OR_Estimates', as.character(thresh), sep = '_')
  temp_name <- paste(temp_name, '.pdf', sep = '')
  
  plot_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
  pdf(plot_dir) 
  
  i <- 0 
  wow <- graph_index - 1
  while(i < wow){
    if(wow - i == 1){
      grid.arrange(graphs[[i+1]], layout_matrix = lay2)    
    }
    if(wow - i == 2){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], layout_matrix = lay2)    
    }  
    if(wow - i == 3){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], 
                   graphs[[i+3]], layout_matrix = lay2)    
    }  
    if(wow - i >= 4){
      grid.arrange(graphs[[i+1]], 
                   graphs[[i+2]], 
                   graphs[[i+3]], 
                   graphs[[i+4]], layout_matrix = lay2)    
    }    
  
    i <- i + 4
  }
  
  dev.off()
}
```