---
title: "summer"
author: "Jasen"
date: "7/7/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(geepack)
library(scales)
library(reshape2)
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Code/00_Codes.R", sep = '')
source(codes_dir)
```

# load the data

```{r}
dir <- getwd()
codes_dir <- paste(substr(dir,1, nchar(dir)-4), "Data/long_temporal_data_V012522.RData", sep = '')
load(codes_dir)
```

#creating longitudinal model

```{r}
nepsy_thresh <- c(5)

thresholds <- c(7, 8, # aac, rsc
                5, 4, 6, # iic, inc, isc
                5, 5,    # cits, snc
                6, 7,    # mffts, mffdts
                8, 7,    # dcgts, gpts
                8, 6, 7, 6, 7, 8)

thresholds <- c(5, 5, # aac, rsc
                5, 5, 6, # iic, inc, isc
                5, 5,    # cits, snc
                5, 5,    # mffts, mffdts
                5, 5,    # dcgts, gpts
                5, 5, 5, 5, 5, 5)

response_vars <- c('aac', 'rsc', 'iic', 'inc', 'isc', 'cits', 'snc', 'mffts', 'mffdts', 'dcgts', 'gpts',
                   'auditory_attention_response_set', 'inhibition',
                   'attention_inhibitory_control', 'language', 'memory_and_learning', 'visuospatial_processing')

#restricting to a and c timepoints

df3_long <- df2_long 
df3_long$Index <- factor(df3_long$Index, levels = c(1,2,3))

# two_levels <- c(F,F,F,F,F,T,T,T,T,T,T,
#                 F,T,T,T)

area_var <- c('50','100','150','200','300','500','1000')
area_var <- paste('ha_', area_var, sep = '')
area_var <- paste(area_var, 'm', sep = '')
area_var_log <- paste(area_var, '_log', sep = '')
area_var_scaled <- paste(area_var, '_scaled', sep = '')
area_var_scaled_log <- paste(area_var, '_scaled_log', sep = '')

distance_vars <- c('dist_house_plant', 'dist_house_plant_log', area_var, area_var_log, area_var_scaled, area_var_scaled_log)
distance_vars <- c('dist_house_plant_log', area_var_log)

distance_vars_graph <- c('Distance', 'Area 50m', 'Area 100m', 'Area 150m', 'Area 200m', 'Area 300m' ,'Area 500m', 'Area 1000m')

pvalues <- data.frame()
estimates <- data.frame()
lows <- data.frame()
highs <- data.frame()
CIs <- data.frame()
num_lows <- data.frame()    # for each score, how many are <= 5
num_totals <- data.frame()  # for each score, how many total exams are there
pct_lows <- data.frame()    # for each score, find pct of <= 5 scores

temp_name <- 'Figures/Final/5e_Neurobehavioral_Temporal_Models.txt'

output_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
sink(output_dir)


for(k in 1:length(response_vars)){ # 1) for each NEPSY score
  
  thresh <- thresholds[k]
  
  pval_array <- c()
  est_array <- c()
  low_array <- c()
  high_array <- c()
  ci_array <- c()
  num_low_array <- c()
  num_total_array <- c()
  pct_low_array <- c()
  
  for(j in distance_vars){ # 2) for each distance/area var
    
    covariates <- c('age', 'race', 'gender', 'Index', 'zha', 'i_g4salary_scaled',  'i_d9educatpar', 'currentnoflorag', 'days_after_mdh')
    
    i <- response_vars[k]
    
    important_vars <- c('nid', covariates, i, j)
    
    if(i == 'iic' | i == 'isc' | i == 'inhibition'){
      important_vars <- append(important_vars, 'inc')
      covariates <- append(covariates, 'inc')
    }
    if(i == 'mffdts' | i == 'memory_and_learning'){
      important_vars <- append(important_vars, 'mffts')
      covariates <- append(covariates, 'mffts')
    }
    
    
    
    df4_long <- df3_long %>% select(important_vars) %>% na.omit()
    
    if(0 %in% table(df4_long$Index)){
      df4_long$Index <- factor(df4_long$Index, levels = c(1,3))
    }
    
    binary_outcome <- paste(i, 'binary', sep = '_')
    
    # df4_long <- df4_long %>% mutate(!!as.name(binary_outcome) := (!!as.name(i) <= thresh)) ## switched from > thresh to <= to measure how doubling area lead to more low scores. 
    
    # bottom 15%, for each grouping of gender and time-period
    
    df4_long <- df4_long %>%
      group_by(gender, Index) %>%
      mutate(
        cutoff = quantile(!!as.name(i), probs = 0.15, na.rm = TRUE),
        !!as.name(binary_outcome) := if_else(!!as.name(i) <= cutoff, 1, 0)
      ) %>%
      ungroup() %>%
      select(-cutoff)  # optional, remove cutoff column if not needed    
    
    
    num_low <- sum(dplyr::pull(df4_long, binary_outcome))
    num_total <- length(dplyr::pull(df4_long, binary_outcome))
    
    eq <- paste(binary_outcome, j, sep = ' ~ ')
    temp <- paste(covariates, collapse = ' + ')
    eq <- paste(eq, temp, sep = ' + ')
    
    m <- geeglm(formula = formula(eq), id = nid, data=df4_long,
                family=binomial(link = 'logit'), corstr="exchangeable")
    s <- summary(m)
    
    
    
    s_coeffs <- s$coefficients
    s_confint <- broom::tidy(m, conf.int = T)
    
    temp_est <- as.numeric(s_confint[2,2])
    temp_lower <- as.numeric(s_confint[2,6])
    temp_upper <- as.numeric(s_confint[2,7])
    
    temp_CI <- paste(round(exp(temp_est * log(2)) , 3), round(exp(temp_lower * log(2)),3), sep = ' (')
    temp_CI <- paste(temp_CI, round(exp(temp_upper * log(2)), 3), sep = ', ')
    temp_CI <- paste(temp_CI, ')', sep = '')
    
    pvalue <- s_coeffs[2,4]
    
    beta_sign_positive <- (s_coeffs[2,1] > 0)
    if(beta_sign_positive){
      the_sign <- 1
    } else{
      the_sign <- -1
    }
    
    pval_array <- append(pval_array, pvalue * the_sign)
    est_array <- append(est_array, round(exp(temp_est * log(2)), 3))
    low_array <- append(low_array, round(exp(temp_lower * log(2)), 3))
    high_array <- append(high_array, round(exp(temp_upper * log(2)), 3))
    ci_array <- append(ci_array, temp_CI)
    
    
    
    num_low_array <- append(num_low_array, num_low)
    num_total_array <- append(num_total_array, num_total)
    pct_low_array <- append(pct_low_array, 100 * num_low/num_total)
    
    
    # print results to txt file
    
    print(eq)
    print(table(df4_long$Index))
    
    print(table(dplyr::pull(df4_long, binary_outcome)))
    
    print(s)
    print('-------------------------------')
  }
  pvalues <- rbind(pvalues, pval_array)
  estimates <- rbind(estimates, est_array)
  lows <- rbind(lows, low_array)
  highs <- rbind(highs, high_array)
  CIs <- rbind(CIs, ci_array)
  
  num_lows <- rbind(num_lows, num_low_array)
  num_totals <- rbind(num_totals, num_total_array)
  pct_lows <- rbind(pct_lows, pct_low_array)
}
sink()
```



#create pvalue matrix


```{r}
# confidence interval result

CIs2 <- t(CIs)
rownames(CIs2) <- distance_vars
colnames(CIs2) <- response_vars

temp_name <- 'Figures/Final/5e_NEPSY_OR_Estimates.csv'


name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(CIs2, file = data_dir)

# pvalue result

pvalues2 <- t(pvalues)
rownames(pvalues2) <- distance_vars
colnames(pvalues2) <- response_vars

temp_name <- 'Figures/Final/5e_NEPSY_Pvalues.csv'

name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(pvalues2, file = data_dir)

# pvalue significant result

pvalues3 <- pvalues2
pvalues3[abs(pvalues3) > 0.05] <- NA

temp_name <- 'Figures/Final/5e_NEPSY_Pvalues_significant.csv'

name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(pvalues3, file = data_dir)

# proportion of scores <= 5 result

pct_lows2 <- t(pct_lows)
rownames(pct_lows2) <- distance_vars
colnames(pct_lows2) <- response_vars

temp_name <- 'Figures/Final/5e_NEPSY_OR_Pct_Low.csv'

name <- c(temp_name)
data_dir <- paste(substr(dir,1, nchar(dir)-4), name, sep = '')
write.csv(pct_lows2, file = data_dir)

```


# create figures

```{r}

highs2 <- t(highs)
rownames(highs2) <- distance_vars
colnames(highs2) <- paste(response_vars, 'high', sep = '_')

lows2 <- t(lows)
rownames(lows2) <- distance_vars
colnames(lows2) <- paste(response_vars, 'low', sep = '_')

estimates2 <- t(estimates)
rownames(estimates2) <- distance_vars
colnames(estimates2) <- paste(response_vars, 'est', sep = '_')

estimates3 <- as.data.frame(estimates2)
lows3 <- as.data.frame(lows2)
highs3 <- as.data.frame(highs2)
 

temp_name <- factor(rownames(estimates3), levels = c('dist_house_plant_log', 'ha_50m_log', 'ha_100m_log', 'ha_150m_log', 'ha_200m_log', 'ha_300m_log', 'ha_500m_log', 'ha_1000m_log'))

all_results <- cbind(estimates3, lows3, highs3)
all_results <- all_results %>% mutate(var_name = temp_name) %>%
  mutate(sig_line = rep(1,nrow(all_results)))

all_results_2 <- all_results
all_results_2$var_name <- all_results$var_name

all_results_2$aac_sig <- c('', '', '', '', '', '', '', '')
all_results_2$rsc_sig <- c('', '', '', '', '', '', '', '')
all_results_2$iic_sig <- c('*', '*', '*', '*', '*', '*', '', '')
all_results_2$inc_sig <- c('', '', '', '', '', '', '', '')
all_results_2$isc_sig <- c('', '', '', '', '', '', '', '')
all_results_2$cits_sig <- c('*', '', '', '', '', '', '', '')
all_results_2$snc_sig <- c('', '', '', '', '', '', '', '')
all_results_2$mffts_sig <- c('', '', '', '', '', '', '', '')
all_results_2$mffdts_sig <- c('', '', '', '', '', '', '*', '')
all_results_2$dcgts_sig <- c('', '', '', '', '', '', '', '')
all_results_2$gpts_sig <- c('', '', '', '', '', '', '', '')
all_results_2$auditory_attention_response_set_sig <- c('', '', '', '', '', '', '', '')
all_results_2$inhibition_sig <- c('', '', '', '', '', '', '', '')
all_results_2$attention_inhibitory_control_sig <- c('*', '*', '*', '*', '', '*', '', '')
all_results_2$language_sig <- c('', '', '', '', '', '*', '', '')
all_results_2$memory_and_learning_sig <- c('', '*', '', '', '', '', '*', '')
all_results_2$visuospatial_processing_sig <- c('', '', '', '', '', '', '', '')


nepsy_graph_names <- c('AAC', 'RSC', 'IIC', 'INC', 'ISC', 'CITS', 'SNC', 'MFFTS', 'MFFDTS', 'DCGTS',
                       'GPTS', 'Auditory Attention Response Set Subdomain',
                       'Inhibition Subdomain',
                       'Attention Inhibitory Control Domain',
                       'Language Domain',
                       'Memory and Learning Domain',
                       'Visuospacial Processing Domain')

graphs <- list()
graph_index <- 1

for(j in 1:length(response_vars)){
  graph_name <- nepsy_graph_names[j]
  i <- response_vars[j]
  sig_name <- paste(i, 'sig', sep = '_')
  est_name <- paste(i, 'est', sep = '_')
  low_name <- paste(i, 'low', sep = '_')
  high_name <- paste(i, 'high', sep = '_')
  temp_title <- paste(toupper(i), 'NEPSY Score', sep = ' ')
  
  g1 <- ggplot(data = all_results_2) +
    geom_errorbar(aes(x = var_name, y = !!as.name(est_name), ymin = !!as.name(low_name), ymax = !!as.name(high_name)), width = 0.5) + 
    geom_point(aes(x = var_name, y = !!as.name(est_name))) + 
    geom_hline(aes(yintercept = 1), linetype = "dashed", color = 'red') + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
    scale_x_discrete(labels = distance_vars_graph) + 
    ylab(graph_name) + 
    xlab('Variable') +
    geom_text(aes(x = var_name,
                      y = !!as.name(high_name) + 0.01,
                      label = !!as.name(sig_name)),
                      position = position_dodge(0.5),
                      size = 6)
  
  graphs[[graph_index]] <- g1
  graph_index <- graph_index + 1
}




  
lay2 <- rbind(c(1,2),
              c(3,4))

temp_name <- 'Figures/Final/5e_NEPSY_Model_OR_Estimates.pdf'

plot_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
pdf(plot_dir) 

i <- 0 
wow <- graph_index - 1
while(i < wow){
  if(wow - i == 1){
    grid.arrange(graphs[[i+1]], layout_matrix = lay2)    
  }
  if(wow - i == 2){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], layout_matrix = lay2)    
  }  
  if(wow - i == 3){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], 
                 graphs[[i+3]], layout_matrix = lay2)    
  }  
  if(wow - i >= 4){
    grid.arrange(graphs[[i+1]], 
                 graphs[[i+2]], 
                 graphs[[i+3]], 
                 graphs[[i+4]], layout_matrix = lay2)    
  }    

  i <- i + 4
}

dev.off()

```

# save only the significant ones

```{r}
temp_name <- 'Figures/Final/5e_NEPSY_Model_OR_Estimates_SIG.pdf'

plot_dir <- paste(substr(dir,1, nchar(dir)-4), temp_name, sep = '')
pdf(plot_dir, width = 10.5, height = 7) 

grid.arrange(graphs[[3]], graphs[[6]], graphs[[9]],     # IIC, CITS, MFFDTS
             graphs[[14]], graphs[[15]], graphs[[16]], # attention inhib, Language, Memory
             
             nrow = 2, ncol = 3) # memory and MFFDTS

dev.off()
```